# Generated by Django 4.2.28 on 2026-02-05 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('req_tech', models.IntegerField(blank=True, null=True)),
                ('req_hand', models.IntegerField(blank=True, null=True)),
                ('req_speed', models.IntegerField(blank=True, null=True)),
                ('req_art', models.IntegerField(blank=True, null=True)),
                ('req_biz', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(default='legendary', max_length=20)),
                ('color_primary', models.CharField(default='#FFD700', max_length=7)),
                ('color_secondary', models.CharField(default='#FFA500', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
            },
        ),
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('Unranked', 'Unranked'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond')], default='Unranked', max_length=20)),
                ('xp', models.IntegerField(default=0)),
                ('stat_tech', models.IntegerField(default=10, help_text='Tech: Diagnosis/Logic')),
                ('stat_hand', models.IntegerField(default=10, help_text='Hand: Craftsmanship/Repair')),
                ('stat_speed', models.IntegerField(default=10, help_text='Speed: Efficiency')),
                ('stat_art', models.IntegerField(default=10, help_text='Art: Detailing/Esthetics')),
                ('stat_biz', models.IntegerField(default=10, help_text='Biz: Sales/Management')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mechanic Profile',
                'verbose_name_plural': 'Mechanic Profiles',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stat_type', models.CharField(choices=[('Tech', 'Tech'), ('Hand', 'Hand'), ('Speed', 'Speed'), ('Art', 'Art'), ('Biz', 'Biz')], max_length=10)),
                ('stat_reward', models.IntegerField(default=1, help_text='Stat points rewarded on completion')),
                ('xp_reward', models.IntegerField(default=10, help_text='XP rewarded on completion')),
                ('requires_photo', models.BooleanField(default=False)),
                ('is_daily', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='api.mechanicprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
            options={
                'verbose_name': 'Task Completion',
                'verbose_name_plural': 'Task Completions',
            },
        ),
        migrations.CreateModel(
            name='UnlockedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobcard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_cards', to='api.mechanicprofile')),
            ],
            options={
                'verbose_name': 'Unlocked Card',
                'verbose_name_plural': 'Unlocked Cards',
                'unique_together': {('profile', 'card')},
            },
        ),
    ]
