# Generated by Django 4.2.28 on 2026-02-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_comment_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_stat', models.CharField(choices=[('Tech', 'Tech'), ('Hand', 'Hand'), ('Speed', 'Speed'), ('Art', 'Art'), ('Biz', 'Biz')], max_length=10)),
                ('stat_reward', models.IntegerField(default=2, help_text='Stat points rewarded')),
                ('xp_reward', models.IntegerField(default=20, help_text='XP rewarded')),
                ('icon', models.CharField(default='Wrench', help_text='Lucide icon name', max_length=50)),
                ('category', models.CharField(choices=[('Daily', '일일 미션'), ('Weekly', '주간 미션'), ('Challenge', '도전 과제'), ('Special', '특별 미션')], default='Daily', max_length=20)),
                ('requires_photo', models.BooleanField(default=True)),
                ('cooldown_hours', models.IntegerField(default=24, help_text='Hours before quest can be repeated')),
                ('max_daily_completions', models.IntegerField(default=1)),
                ('difficulty', models.IntegerField(default=1, help_text='1-5 difficulty rating')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
                'ordering': ['order', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='quest_proofs/')),
                ('proof_image_url', models.URLField(blank=True, help_text='External image URL if not using upload', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from user')),
                ('is_verified', models.BooleanField(default=True, help_text='Auto-verified or admin verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to='api.mechanicprofile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.quest')),
            ],
            options={
                'verbose_name': 'Quest Completion',
                'verbose_name_plural': 'Quest Completions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
