import type { Academy, Course, CourseCategory } from '@/types';

// ============ ACADEMIES ============
export const academies: Academy[] = [
  {
    id: 'polytech',
    name: '한국폴리텍대학',
    logo: '🏫',
    description: '국가기술자격 취득을 위한 공인 교육기관. 국비지원 100% 무료 과정 다수.',
    location: '전국 캠퍼스',
    isPartner: true,
    website: 'https://www.kopo.ac.kr',
  },
  {
    id: 'unsan',
    name: '운산 아카데미',
    logo: '🔧',
    description: '자동차 애프터마켓 전문 실무 교육. 현장 중심 커리큘럼.',
    location: '경기도 용인',
    isPartner: true,
    website: 'https://unsan.academy',
  },
  {
    id: 'ev_master',
    name: 'EV마스터 교육원',
    logo: '⚡',
    description: '전기차/하이브리드 특화 교육 전문. 고전압 안전교육 인증기관.',
    location: '서울 강남',
    isPartner: true,
    website: 'https://evmaster.kr',
  },
  {
    id: 'jdetail',
    name: "J's Detailing Academy",
    logo: '✨',
    description: '프리미엄 디테일링 & PPF 전문 교육. 억대 연봉 시공사 배출.',
    location: '서울 성수',
    isPartner: false,
  },
  {
    id: 'tuning_pro',
    name: '튜닝프로 아카데미',
    logo: '🏎️',
    description: 'ECU 튜닝 & 퍼포먼스 전문. WinOLS 공식 교육기관.',
    location: '경기도 화성',
    isPartner: false,
  },
  {
    id: 'online_auto',
    name: '오토러닝',
    logo: '💻',
    description: '자동차 온라인 교육 플랫폼. 언제 어디서나 학습 가능.',
    location: '온라인',
    isPartner: true,
    website: 'https://autolearning.kr',
  },
  {
    id: 'kasa',
    name: '한국자동차정비학원',
    logo: '🛠️',
    description: '자동차정비기능사/산업기사 전문 양성기관.',
    location: '서울/경기',
    isPartner: true,
    website: 'https://kasa.ac.kr',
  },
  {
    id: 'wrap_korea',
    name: '랩코리아 아카데미',
    logo: '🎨',
    description: '랩핑/PPF 전문 교육. 3M/Avery 공식 인증 교육기관.',
    location: '인천 청라',
    isPartner: false,
  },
  {
    id: 'camper_school',
    name: '캠핑카 스쿨',
    logo: '🚐',
    description: '캠핑카 제작/개조 전문 교육. 창업 지원 프로그램 운영.',
    location: '충남 천안',
    isPartner: false,
  },
  {
    id: 'body_master',
    name: '바디마스터 아카데미',
    logo: '🔩',
    description: '판금/도장/PDR 전문 교육. 보험사 협력 실습.',
    location: '경기도 평택',
    isPartner: false,
  },
];

// ============ COURSES ============
export const courses: Course[] = [
  // ========== EV/Future Courses ==========
  {
    id: 'course_ev_01',
    academyId: 'polytech',
    title: '전기차 고전압 안전교육 (법정필수)',
    description: '전기차 정비 전 필수 이수 과정. 고전압 시스템 이해 및 안전 작업 절차 교육. 감전사고 예방 및 응급처치.',
    targetJobIds: ['ev_01', 'ev_02', 'ev_03', 'ev_04', 'ev_05', 'ev_06', 'maint_17'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '2일 (16시간)',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '법정필수', '자격증'],
    certifications: ['고전압 안전교육 이수증'],
    url: 'https://www.kopo.ac.kr/ev-safety',
    rating: 4.8,
    enrollCount: 1250,
  },
  {
    id: 'course_ev_02',
    academyId: 'ev_master',
    title: 'EV 배터리 진단 마스터 과정',
    description: '배터리 SOH 진단, 셀 밸런싱, BMS 분석 실무 교육. 현장 장비 활용 실습 중심. 테슬라/현대 차량 실습.',
    targetJobIds: ['ev_01', 'ev_05'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '4주 (주말반)',
    price: 180,
    priceNote: '내일배움카드 50% 지원',
    tags: ['내일배움카드', '실습위주', '주말반', '취업연계'],
    url: 'https://evmaster.kr/battery',
    rating: 4.9,
    enrollCount: 320,
  },
  {
    id: 'course_ev_03',
    academyId: 'unsan',
    title: 'ADAS 캘리브레이션 전문가 과정',
    description: '카메라/레이더 센서 보정 실무. 주요 차종별 캘리브레이션 장비 운용법. Autel/Hunter 장비 실습.',
    targetJobIds: ['ev_03', 'ev_09'],
    category: 'EV_Future',
    type: 'Hybrid',
    duration: '3주',
    price: 150,
    tags: ['실습위주', '장비지원', '취업연계'],
    url: 'https://unsan.academy/adas',
    rating: 4.7,
    enrollCount: 180,
  },
  {
    id: 'course_ev_04',
    academyId: 'ev_master',
    title: 'EV 모터 & 감속기 정비 과정',
    description: '전기차 구동계 구조 이해 및 오버홀 실습. 모터 진단, 감속기 분해조립.',
    targetJobIds: ['ev_02'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '2주',
    price: 120,
    tags: ['실습위주', '고급과정'],
    url: 'https://evmaster.kr/motor',
    rating: 4.6,
    enrollCount: 95,
  },
  {
    id: 'course_ev_05',
    academyId: 'polytech',
    title: '충전 인프라 유지보수 기술자 양성과정',
    description: '급속/완속 충전기 설치 및 유지보수. 전기 안전 규정, 고장 진단 및 수리.',
    targetJobIds: ['ev_04'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '3주',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '취업연계', '블루오션'],
    certifications: ['충전기 유지보수 자격'],
    url: 'https://www.kopo.ac.kr/ev-charger',
    rating: 4.5,
    enrollCount: 210,
  },
  {
    id: 'course_ev_06',
    academyId: 'ev_master',
    title: '폐배터리 진단 및 재사용 평가 과정',
    description: '폐차 EV 배터리 상태 진단. ESS 재사용 등급 판정. 순환경제 시대 블루오션.',
    targetJobIds: ['ev_05'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '2주',
    price: 100,
    tags: ['친환경', '블루오션', '미래직업'],
    url: 'https://evmaster.kr/recycle',
    rating: 4.7,
    enrollCount: 78,
  },
  {
    id: 'course_ev_07',
    academyId: 'online_auto',
    title: '하이브리드 시스템 이해와 진단',
    description: '하이브리드 구조 이해. 엔진-모터 협조 제어 진단. EV 전환을 위한 징검다리 과정.',
    targetJobIds: ['maint_17'],
    category: 'EV_Future',
    type: 'Online',
    duration: '4주',
    price: 50,
    tags: ['온라인', '입문추천', 'EV전환'],
    url: 'https://autolearning.kr/hybrid',
    rating: 4.4,
    enrollCount: 890,
  },
  {
    id: 'course_ev_08',
    academyId: 'ev_master',
    title: 'EV 화재 안전 관리자 양성과정',
    description: '전기차 화재 특성 이해. 전용 소화 장비 운용. 격리 구역 설정 및 관리.',
    targetJobIds: ['ev_06'],
    category: 'EV_Future',
    type: 'Offline',
    duration: '3일',
    price: 80,
    tags: ['안전', '필수교육', '자격증'],
    certifications: ['EV 화재안전 관리자'],
    url: 'https://evmaster.kr/fire-safety',
    rating: 4.8,
    enrollCount: 145,
  },

  // ========== Maintenance Courses ==========
  {
    id: 'course_maint_01',
    academyId: 'polytech',
    title: '자동차정비기능사 취득과정',
    description: '국가공인 자동차정비기능사 자격증 취득을 위한 이론 및 실기 교육. 정비사 필수 자격증.',
    targetJobIds: ['maint_01', 'maint_02', 'maint_04', 'maint_06'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '6개월',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '자격증', '취업연계'],
    certifications: ['자동차정비기능사'],
    url: 'https://www.kopo.ac.kr/auto-cert',
    rating: 4.5,
    enrollCount: 2800,
  },
  {
    id: 'course_maint_02',
    academyId: 'unsan',
    title: '수입차 진단 스페셜리스트',
    description: '벤츠/BMW/아우디 전용 진단기 운용 및 고급 진단 기법 교육. STAR/ISTA 실습.',
    targetJobIds: ['maint_14', 'maint_17', 'niche_06'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '2주',
    price: 120,
    tags: ['프리미엄', '실습위주', '수료증'],
    url: 'https://unsan.academy/diag-pro',
    rating: 4.8,
    enrollCount: 450,
  },
  {
    id: 'course_maint_03',
    academyId: 'tuning_pro',
    title: 'ECU 맵핑 & 튜닝 마스터',
    description: '출력 향상을 위한 ECU 데이터 분석 및 맵핑 기법. WinOLS 실습. 고급 과정.',
    targetJobIds: ['maint_15'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '4주',
    price: 250,
    tags: ['고급과정', '장비지원', '소수정예'],
    url: 'https://tuningpro.kr/ecu',
    rating: 4.9,
    enrollCount: 85,
  },
  {
    id: 'course_maint_04',
    academyId: 'kasa',
    title: '에어컨/공조 시스템 전문가 과정',
    description: '자동차 에어컨 시스템 진단 및 수리. 냉매 관리, 컴프레서 오버홀. 계절 수요 높음.',
    targetJobIds: ['maint_06'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '2주',
    price: 80,
    tags: ['계절수요', '실습위주'],
    url: 'https://kasa.ac.kr/aircon',
    rating: 4.5,
    enrollCount: 320,
  },
  {
    id: 'course_maint_05',
    academyId: 'kasa',
    title: '휠 얼라인먼트 & 하체 정비',
    description: '휠 얼라인먼트 장비 운용. 서스펜션 진단 및 교체. 하체 소음 해결.',
    targetJobIds: ['maint_03', 'maint_05'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '1주',
    price: 60,
    tags: ['하체전문', '실습위주'],
    url: 'https://kasa.ac.kr/alignment',
    rating: 4.6,
    enrollCount: 280,
  },
  {
    id: 'course_maint_06',
    academyId: 'polytech',
    title: '변속기 오버홀 마스터 과정',
    description: '자동/수동 변속기 분해조립 및 오버홀. 클러치 교환. 희소가치 높은 기술.',
    targetJobIds: ['maint_09'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '4주',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '희소가치', '장인기술'],
    url: 'https://www.kopo.ac.kr/transmission',
    rating: 4.7,
    enrollCount: 120,
  },
  {
    id: 'course_maint_07',
    academyId: 'polytech',
    title: '엔진 오버홀 전문가 과정',
    description: '엔진 헤드/블록 가공. 피스톤 링 교환. 타이밍 정렬. 정비의 꽃.',
    targetJobIds: ['maint_10'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '6주',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '장인기술', '고급과정'],
    url: 'https://www.kopo.ac.kr/engine-overhaul',
    rating: 4.8,
    enrollCount: 95,
  },
  {
    id: 'course_maint_08',
    academyId: 'polytech',
    title: '자동차 검사원 양성과정',
    description: '정기/종합 검사 수행을 위한 국가 자격 취득 과정. 법규 및 검사 실무.',
    targetJobIds: ['maint_11'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '3주',
    price: 0,
    priceNote: '국비지원 100%',
    tags: ['국비지원', '자격증필수', '안정적'],
    certifications: ['자동차 검사원 자격'],
    url: 'https://www.kopo.ac.kr/inspector',
    rating: 4.4,
    enrollCount: 450,
  },
  {
    id: 'course_maint_09',
    academyId: 'online_auto',
    title: '타이어 & 브레이크 기초',
    description: '타이어 탈부착, 밸런스 교정. 브레이크 패드/디스크 교환. 입문자 필수.',
    targetJobIds: ['maint_02', 'maint_04'],
    category: 'Maintenance',
    type: 'Online',
    duration: '2주',
    price: 30,
    tags: ['온라인', '입문추천', '기초'],
    url: 'https://autolearning.kr/tire-brake',
    rating: 4.3,
    enrollCount: 1500,
  },
  {
    id: 'course_maint_10',
    academyId: 'tuning_pro',
    title: '배기 튜닝 & 용접 마스터',
    description: '커스텀 배기 라인 제작. 스테인리스 용접. 사운드 튜닝 기법.',
    targetJobIds: ['maint_16'],
    category: 'Maintenance',
    type: 'Offline',
    duration: '2주',
    price: 150,
    tags: ['용접', '커스텀', '사운드'],
    url: 'https://tuningpro.kr/exhaust',
    rating: 4.7,
    enrollCount: 110,
  },

  // ========== Body/Detailing Courses ==========
  {
    id: 'course_body_01',
    academyId: 'jdetail',
    title: 'PPF 인스톨러 입문과정',
    description: 'PPF 시공의 기초부터 핸드컷 기법까지. 억대 연봉 PPF 전문가로의 첫 걸음.',
    targetJobIds: ['film_03', 'film_01'],
    category: 'Body',
    type: 'Offline',
    duration: '2주',
    price: 200,
    tags: ['실습위주', '재료비포함', '취업연계'],
    url: 'https://jdetailing.kr/ppf-basic',
    rating: 4.7,
    enrollCount: 380,
  },
  {
    id: 'course_body_02',
    academyId: 'jdetail',
    title: 'PPF 마스터 과정 (고급)',
    description: '복잡한 곡면 시공, 범퍼/사이드미러 완벽 마감. 프리미엄 필름 다루기.',
    targetJobIds: ['film_03'],
    category: 'Body',
    type: 'Offline',
    duration: '4주',
    price: 350,
    tags: ['고급과정', '소수정예', '억대연봉'],
    url: 'https://jdetailing.kr/ppf-master',
    rating: 5.0,
    enrollCount: 120,
  },
  {
    id: 'course_body_03',
    academyId: 'jdetail',
    title: '프리미엄 디테일링 & 코팅',
    description: '광택, 세라믹 코팅, 가죽 복원 등 프리미엄 디테일링 전과정.',
    targetJobIds: ['body_01', 'body_09'],
    category: 'Body',
    type: 'Offline',
    duration: '1주',
    price: 80,
    tags: ['입문추천', '재료비포함'],
    url: 'https://jdetailing.kr/detailing',
    rating: 4.6,
    enrollCount: 650,
  },
  {
    id: 'course_body_04',
    academyId: 'body_master',
    title: 'PDR (무도장 덴트 복원) 마스터',
    description: '도색 없이 찌그러짐 복원하는 PDR 기술. 로드/글루 풀링 기법. 보험 연계 실습.',
    targetJobIds: ['body_02'],
    category: 'Body',
    type: 'Offline',
    duration: '4주',
    price: 280,
    tags: ['실습위주', '보험연계', '고수익'],
    url: 'https://bodymaster.kr/pdr',
    rating: 4.8,
    enrollCount: 180,
  },
  {
    id: 'course_body_05',
    academyId: 'body_master',
    title: '판금 & 용접 기초과정',
    description: '차체 프레임 교정 기초. 스팟 용접, CO2 용접 실습.',
    targetJobIds: ['body_03', 'body_06'],
    category: 'Body',
    type: 'Offline',
    duration: '3주',
    price: 150,
    tags: ['기초', '용접', '실습위주'],
    url: 'https://bodymaster.kr/panel',
    rating: 4.5,
    enrollCount: 220,
  },
  {
    id: 'course_body_06',
    academyId: 'body_master',
    title: '자동차 도장 기술자 양성과정',
    description: '스프레이 건 운용, 도료 배합, 열처리. 예술적 감각 필요.',
    targetJobIds: ['body_04', 'body_05'],
    category: 'Body',
    type: 'Offline',
    duration: '6주',
    price: 200,
    tags: ['예술성', '실습위주', '자격증'],
    certifications: ['자동차도장기능사'],
    url: 'https://bodymaster.kr/paint',
    rating: 4.6,
    enrollCount: 145,
  },
  {
    id: 'course_body_07',
    academyId: 'unsan',
    title: '자동차 유리 & ADAS 연계 과정',
    description: '유리 교환 기술 + ADAS 캘리브레이션 연계. 블루오션 조합.',
    targetJobIds: ['body_07', 'ev_03'],
    category: 'Body',
    type: 'Offline',
    duration: '2주',
    price: 130,
    tags: ['블루오션', '조합과정', '취업연계'],
    url: 'https://unsan.academy/glass-adas',
    rating: 4.7,
    enrollCount: 95,
  },
  {
    id: 'course_body_08',
    academyId: 'body_master',
    title: '휠 복원 & 다이아컷팅 전문가',
    description: '휠 굴절 수리, 다이아컷팅 장비 운용. 휠 도색 기법.',
    targetJobIds: ['body_08'],
    category: 'Body',
    type: 'Offline',
    duration: '2주',
    price: 180,
    tags: ['틈새시장', '장비포함', '고수익'],
    url: 'https://bodymaster.kr/wheel',
    rating: 4.8,
    enrollCount: 110,
  },
  {
    id: 'course_body_09',
    academyId: 'jdetail',
    title: '실내 복원 & 가죽 클리닝',
    description: '가죽/직물 시트 복원, 플라스틱 복원. 실내 냄새 제거.',
    targetJobIds: ['body_09'],
    category: 'Body',
    type: 'Offline',
    duration: '3일',
    price: 50,
    tags: ['입문추천', '디테일링'],
    url: 'https://jdetailing.kr/interior',
    rating: 4.5,
    enrollCount: 320,
  },
  {
    id: 'course_body_10',
    academyId: 'body_master',
    title: '테슬라 공인 바디샵 준비과정',
    description: '알루미늄 바디 용접 기술. Tesla 인증 취득 준비. 프리미엄 브랜드.',
    targetJobIds: ['body_12'],
    category: 'Body',
    type: 'Offline',
    duration: '4주',
    price: 350,
    tags: ['테슬라', '알루미늄', '프리미엄'],
    url: 'https://bodymaster.kr/tesla-body',
    rating: 4.9,
    enrollCount: 65,
  },
  {
    id: 'course_body_11',
    academyId: 'body_master',
    title: '올드카 리스토어 입문과정',
    description: '클래식카 복원 기초. 부품 직구, 녹 제거, 원형 보존 기법.',
    targetJobIds: ['body_11'],
    category: 'Body',
    type: 'Offline',
    duration: '2주',
    price: 200,
    tags: ['희소가치', '클래식', '장인'],
    url: 'https://bodymaster.kr/classic',
    rating: 4.7,
    enrollCount: 45,
  },

  // ========== Tuning/Film Courses ==========
  {
    id: 'course_tuning_01',
    academyId: 'wrap_korea',
    title: '컬러 랩핑 전문가 과정',
    description: '전체 랩핑, 부분 랩핑, 크롬 삭제 등 컬러 체인지 시공 기법. 3M/Avery 필름 실습.',
    targetJobIds: ['film_02', 'film_04'],
    category: 'Tuning',
    type: 'Offline',
    duration: '3주',
    price: 180,
    tags: ['실습위주', '재료비포함', '취업연계'],
    url: 'https://wrapkorea.kr/color-wrap',
    rating: 4.8,
    enrollCount: 290,
  },
  {
    id: 'course_tuning_02',
    academyId: 'camper_school',
    title: '캠핑카 빌더 양성과정',
    description: '스타렉스/카니발 개조, 가구 제작, 전기 시스템 설치 종합 교육. 창업 지원.',
    targetJobIds: ['film_09', 'next_03'],
    category: 'Tuning',
    type: 'Offline',
    duration: '8주',
    price: 350,
    priceNote: '내일배움카드 일부 지원',
    tags: ['내일배움카드', '창업지원', '실습위주'],
    url: 'https://camperschool.kr/builder',
    rating: 4.9,
    enrollCount: 95,
  },
  {
    id: 'course_tuning_03',
    academyId: 'wrap_korea',
    title: '윈도우 틴팅 전문가 과정',
    description: '필름 열성형, 컴퓨터 커팅. 입문에서 고급까지. PPF/랩핑 진출 징검다리.',
    targetJobIds: ['film_01'],
    category: 'Tuning',
    type: 'Offline',
    duration: '1주',
    price: 80,
    tags: ['입문추천', '재료비포함', '빠른취업'],
    url: 'https://wrapkorea.kr/tint',
    rating: 4.6,
    enrollCount: 450,
  },
  {
    id: 'course_tuning_04',
    academyId: 'unsan',
    title: '실내 커스터마이징 과정',
    description: '실내 랩핑, 천장 엠보싱, 트림 튜닝. 창의적인 인테리어 작업.',
    targetJobIds: ['film_05'],
    category: 'Tuning',
    type: 'Offline',
    duration: '2주',
    price: 120,
    tags: ['예술성', '커스텀', '실습위주'],
    url: 'https://unsan.academy/interior-custom',
    rating: 4.7,
    enrollCount: 135,
  },
  {
    id: 'course_tuning_05',
    academyId: 'unsan',
    title: '엠비언트 라이트 & LED 시공',
    description: '실내 무드등 LED 매립 및 배선. 컨트롤러 설정. 트렌디한 튜닝.',
    targetJobIds: ['film_06'],
    category: 'Tuning',
    type: 'Offline',
    duration: '3일',
    price: 60,
    tags: ['트렌디', 'LED', '입문추천'],
    url: 'https://unsan.academy/ambient',
    rating: 4.5,
    enrollCount: 180,
  },
  {
    id: 'course_tuning_06',
    academyId: 'tuning_pro',
    title: '카오디오 & 사운드 시스템 과정',
    description: '스피커/앰프/우퍼 설치. 방음/방진 시공. 취미와 연계되는 직업.',
    targetJobIds: ['film_07'],
    category: 'Tuning',
    type: 'Offline',
    duration: '2주',
    price: 100,
    tags: ['카오디오', '취미연계', '실습위주'],
    url: 'https://tuningpro.kr/audio',
    rating: 4.6,
    enrollCount: 165,
  },
  {
    id: 'course_tuning_07',
    academyId: 'tuning_pro',
    title: '레트로핏 & 순정옵션 이식',
    description: '구형 차에 신형 순정 옵션 이식. CAN 통신 이해. 기술 집약적.',
    targetJobIds: ['film_08'],
    category: 'Tuning',
    type: 'Offline',
    duration: '3주',
    price: 200,
    tags: ['기술집약', '레트로핏', '고급과정'],
    url: 'https://tuningpro.kr/retrofit',
    rating: 4.8,
    enrollCount: 75,
  },

  // ========== Management Courses ==========
  {
    id: 'course_mgmt_01',
    academyId: 'online_auto',
    title: '자동차 서비스어드바이저 과정',
    description: '고객 응대, 견적 작성, 클레임 처리 등 SA 실무 온라인 교육.',
    targetJobIds: ['mgmt_01', 'mgmt_02'],
    category: 'Management',
    type: 'Online',
    duration: '4주',
    price: 30,
    tags: ['온라인', '자기주도', '수료증'],
    url: 'https://autolearning.kr/sa',
    rating: 4.3,
    enrollCount: 1200,
  },
  {
    id: 'course_mgmt_02',
    academyId: 'online_auto',
    title: '중고차 평가사 자격 대비반',
    description: '중고차 평가사 시험 대비 이론 + 실전 모의고사. 합격률 높음.',
    targetJobIds: ['mgmt_06', 'mgmt_07'],
    category: 'Management',
    type: 'Online',
    duration: '8주',
    price: 50,
    priceNote: '합격 시 50% 환급',
    tags: ['온라인', '자격증', '환급제'],
    certifications: ['중고차 평가사'],
    url: 'https://autolearning.kr/used-car',
    rating: 4.5,
    enrollCount: 890,
  },
  {
    id: 'course_mgmt_03',
    academyId: 'online_auto',
    title: '자동차 손해사정사 기초과정',
    description: '사고 과실 비율 및 수리 범위 산정 기초. 자격증 취득 준비.',
    targetJobIds: ['mgmt_05'],
    category: 'Management',
    type: 'Online',
    duration: '12주',
    price: 80,
    tags: ['온라인', '자격증', '고연봉'],
    certifications: ['자동차 손해사정사'],
    url: 'https://autolearning.kr/appraiser',
    rating: 4.4,
    enrollCount: 560,
  },
  {
    id: 'course_mgmt_04',
    academyId: 'kasa',
    title: '정비샵 창업 & 경영과정',
    description: '정비샵 창업 준비. 인허가, 장비 구입, 고객 관리, 손익 분석.',
    targetJobIds: ['mgmt_02'],
    category: 'Management',
    type: 'Offline',
    duration: '2주',
    price: 100,
    tags: ['창업', '경영', '실무'],
    url: 'https://kasa.ac.kr/startup',
    rating: 4.6,
    enrollCount: 320,
  },
  {
    id: 'course_mgmt_05',
    academyId: 'online_auto',
    title: '보증수리(Warranty) 청구 실무',
    description: '제조사/보험사 수리비 청구 행정. 딜러십 필수 스킬.',
    targetJobIds: ['mgmt_04'],
    category: 'Management',
    type: 'Online',
    duration: '2주',
    price: 25,
    tags: ['온라인', '딜러십', '행정'],
    url: 'https://autolearning.kr/warranty',
    rating: 4.2,
    enrollCount: 450,
  },
  {
    id: 'course_mgmt_06',
    academyId: 'online_auto',
    title: '장기렌트/리스 영업 마스터',
    description: '신차 금융 상품 이해 및 영업 기법. 인센티브 극대화 전략.',
    targetJobIds: ['mgmt_08'],
    category: 'Management',
    type: 'Online',
    duration: '3주',
    price: 40,
    tags: ['온라인', '영업', '금융'],
    url: 'https://autolearning.kr/leasing',
    rating: 4.3,
    enrollCount: 680,
  },
];

// ============ HELPER FUNCTIONS ============

export function getAcademyById(id: string): Academy | undefined {
  return academies.find(a => a.id === id);
}

export function getCourseById(id: string): Course | undefined {
  return courses.find(c => c.id === id);
}

export function getCoursesForJob(jobId: string): Course[] {
  return courses.filter(c => c.targetJobIds.includes(jobId));
}

export function getCoursesByCategory(category: CourseCategory): Course[] {
  return courses.filter(c => c.category === category);
}

export function getCoursesByAcademy(academyId: string): Course[] {
  return courses.filter(c => c.academyId === academyId);
}

export function getPartnerAcademies(): Academy[] {
  return academies.filter(a => a.isPartner);
}

export function getFreeCourses(): Course[] {
  return courses.filter(c => c.price === 0);
}

export function getCoursesWithTag(tag: string): Course[] {
  return courses.filter(c => c.tags.includes(tag));
}

// Format price display
export function formatCoursePrice(price: number): string {
  if (price === 0) {
    return '무료';
  }
  return `${price.toLocaleString()}만원`;
}

// Get popular courses (by enrollment)
export function getPopularCourses(limit: number = 5): Course[] {
  return [...courses]
    .sort((a, b) => (b.enrollCount || 0) - (a.enrollCount || 0))
    .slice(0, limit);
}

// Get highly rated courses
export function getTopRatedCourses(limit: number = 5): Course[] {
  return [...courses]
    .sort((a, b) => (b.rating || 0) - (a.rating || 0))
    .slice(0, limit);
}

// Search courses
export function searchCourses(query: string): Course[] {
  const lowerQuery = query.toLowerCase();
  return courses.filter(c =>
    c.title.toLowerCase().includes(lowerQuery) ||
    c.description.toLowerCase().includes(lowerQuery) ||
    c.tags.some(t => t.toLowerCase().includes(lowerQuery))
  );
}
